INSERT INTO CLM (ID,NAME) VALUES (0,'Orange Router');
INSERT INTO CLM (ID,NAME) VALUES (1,'CISCO Router');
INSERT INTO CLM (ID,NAME) VALUES (2,'NetGear Switch');
INSERT INTO CLM (ID,NAME) VALUES (3,'BI CLM');
INSERT INTO CLM (ID,NAME) VALUES (4,'TP-Link');

--INSERT INTO CLM (NAME) VALUES ('Orange Router');